{
 "title": "SciLabs",
 "time": { "from": "2020-11-10T22:57:13.480Z", "to": "2020-11-11T22:48:49.777Z" },
 "panels": [
  {
   "title": "ActiveFeed - BlindFeed: Zählpunkt 51332993950",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(activeFeed) as \"activeFeed\", AVG(blindfeed) as \"blindfeed\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") AND zaehlpunkt = 4\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "EffectiveConsumption - BlindConsumption: Zählpunkt 51332993950",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(effectiveconsumption) as \"effectiveconsumption\", AVG(blindconsumption) as \"blindconsumption\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") and zaehlpunkt = 4\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "ActiveFeed - BlindFeed: Zählpunkt 51332993942",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(activeFeed) as \"activeFeed\", AVG(blindfeed) as \"blindfeed\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") AND zaehlpunkt = 1\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "EffectiveConsumption - BlindConsumption: Zählpunkt 51332993942",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(effectiveconsumption) as \"effectiveconsumption\", AVG(blindconsumption) as \"blindconsumption\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") and zaehlpunkt = 1\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "ActiveFeed - BlindFeed: Zählpunkt 51332994099",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(activeFeed) as \"activeFeed\", AVG(blindfeed) as \"blindfeed\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") AND zaehlpunkt = 3\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "EffectiveConsumption - BlindConsumption: Zählpunkt 51332994099",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(effectiveconsumption) as \"effectiveconsumption\", AVG(blindconsumption) as \"blindconsumption\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") and zaehlpunkt = 3\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "ActiveFeed - BlindFeed: Zählpunkt 51333017254",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(activeFeed) as \"activeFeed\", AVG(blindfeed) as \"blindfeed\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") AND zaehlpunkt = 2\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "EffectiveConsumption - BlindConsumption: Zählpunkt 51333017254",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval()', time) as \"time\",\n  AVG(effectiveconsumption) as \"effectiveconsumption\", AVG(blindconsumption) as \"blindconsumption\"\nFROM zeitreihen\nWHERE $__timeFilter(\"time\") and zaehlpunkt = 2\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}